matrix:
    include:
      - language: node_js
        node_js:
            - "8.10.0"

        before_install:
            - cd AcademicManager-Web
            - npm install

        script:
            - npm run build

        deploy:
            provider: heroku
            api_key: 0d2d6a3a-a07c-4f2b-b209-450f71f35ad6
            app:
                master: cooperatorapp-frontend-18
            on:
                repo: McGill-ECSE321-Winter2019/ecse321-group-project-18

      - language: java

        before_install:
            - chmod +x gradlew

        script:
            - ./gradlew build

        deploy:
            provider: heroku
            api_key: 0d2d6a3a-a07c-4f2b-b209-450f71f35ad6
            app:
                master: cooperatorapp-backend-18
            on:
                repo: McGill-ECSE321-Winter2019/ecse321-group-project-18
      - language: android
      
        before_install:
            - cd AcademicManager-Android
            - chmod +x gradlew
            - yes | sdkmanager "build-tools;28.0.3"
            - yes | sdkmanager "platforms;android-28"
      
        android:
          components:
            # Uncomment the lines below if you want to
            # use the latest revision of Android SDK Tools
            # - tools
            # - platform-tools

            # The BuildTools version used by your project
            - build-tools-28.0.3

            # The SDK version used to compile your project
            - android-28

            # Additional components
            - extra-google-google_play_services
            - extra-google-m2repository
            - extra-android-m2repository


          licenses:
            - 'android-sdk-preview-license-52d11cd2'
            - 'android-sdk-license-.+'
            - 'google-gdk-license-.+'


